#pragma once
#define DXBRIDGE_VERSION_MAJOR  1
#define DXBRIDGE_VERSION_MINOR  0
#define DXBRIDGE_VERSION_PATCH  0
#define DXBRIDGE_VERSION        ((DXBRIDGE_VERSION_MAJOR << 16) | (DXBRIDGE_VERSION_MINOR << 8) | DXBRIDGE_VERSION_PATCH)
#define DXBRIDGE_STRUCT_VERSION 1
