# Detect Windows SDK version
if(DEFINED CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION)
    set(WINDOWS_SDK_VERSION ${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION})
else()
    set(WINDOWS_SDK_VERSION "10.0")
endif()
message(STATUS "Windows SDK: ${WINDOWS_SDK_VERSION}")
